name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*' # Push events to matching 0.*
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          TAG = ${{ github.ref }}
          docker build . --tag ghcr.io/cottand/lemmy-metrics:${TAG:1} 
          docker push ghcr.io/cottand/lemmy-metrics
