name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*' # Push events to matching 0.*
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          TAG=${{ github.ref }}
          docker build -f docker/Dockerfile . --tag ghcr.io/cottand/lemmy-metrics:${TAG:10} --build-arg="CARGO_BUILD_FEATURES=prometheus-metrics" --build-arg="RUST_RELEASE_MODE=release"
          docker push ghcr.io/cottand/lemmy-metrics
